[bootstrap] Create prefix directory with appropriate permissions.
The bootstrap script now checks that <prefix> exists and is rwx by the
user invoking ./bootstrap.

If <prefix> does not exist, it is created with mkdir -p, falling back to
sudo mkdir -p in case of insufficient permissions. If something fails,
the error is printed and the user is asked for manual creation and
bootstrap stops.

If <prefix> is not rw by the user, a message is also printed and
bootstrap stops.

diff --git a/bootstrap/bootstrap b/bootstrap/bootstrap
--- a/bootstrap/bootstrap
+++ b/bootstrap/bootstrap
@@ -108,6 +108,13 @@ run_cmd()
     fi
 }
 
+# run a command verbosely
+echo_cmd()
+{
+    echo "running: $@"
+    eval "$@"
+}
+
 mkdir_p()
 {
     run_cmd "mkdir -p $@"
@@ -203,6 +210,29 @@ if [ -n "$CP" ]; then
 else
     check_prog cpprog cp
 fi
+
+
+# --- create the initial prefix directory ----------------------------
+
+[ -x "$prefix" ] || {
+  echo_msg "Creating ${prefix} directory"
+  echo_cmd mkdir -p "$prefix" 2>/dev/null || {
+    echo failed
+    echo_msg "Becoming root to create ${prefix} directory"
+    echo_cmd sudo mkdir -p "$prefix" &&
+    echo_cmd sudo chown `id -u` "${prefix}"
+  }
+
+  [ -x "$prefix" ] ||
+    die "Please create a directory ${prefix}, writable by you.
+You can also do $0 --prefix <path> to bootstrap with <path> prefix."
+
+  echo_cmd chmod u+rwx "${prefix}" ||
+    die "Could not make ${prefix} writable by you. Please do it manually."
+}
+
+[ -r "$prefix" -a -w "$prefix" ] ||
+  die "Please make ${prefix} readable and writable by you."
 
 
 # --- set up an example mk.conf file ---------------------------------
