[archivers/libarchive] Disable fatal errors for C++ preproc in configure script
This package does not require any C++ preprocessor, so avoid stupid
failures when no c++ preprocessor is installed.

diff --git a/archivers/libarchive/dist/configure b/archivers/libarchive/dist/configure
--- a/archivers/libarchive/dist/configure
+++ b/archivers/libarchive/dist/configure
@@ -6047,11 +6047,11 @@ rm -f conftest.err conftest.$ac_ext
 if $ac_preproc_ok; then
   :
 else
-  { { echo "$as_me:$LINENO: error: C++ preprocessor \"$CXXCPP\" fails sanity check
-See \`config.log' for more details." >&5
-echo "$as_me: error: C++ preprocessor \"$CXXCPP\" fails sanity check
-See \`config.log' for more details." >&2;}
-   { (exit 1); exit 1; }; }
+: # { { echo "$as_me:$LINENO: error: C++ preprocessor \"$CXXCPP\" fails sanity check
+: #See \`config.log' for more details." >&5
+: #echo "$as_me: error: C++ preprocessor \"$CXXCPP\" fails sanity check
+: #See \`config.log' for more details." >&2;}
+: #  { (exit 1); exit 1; }; }
 fi
 
 ac_ext=cpp
