[mk/internal] Make the logfilter script also log to a file even in verbose mode
When the logfilter is configured as a no-op (e.g. with VERBOSE=1), it must
still log to the logfile if specified. This is more complex than it seems
because the exit status of the actual command must be extracted from the pipe
in which the 'tee' to the logfile is run.

diff --git a/mk/internal/logfilter b/mk/internal/logfilter
--- a/mk/internal/logfilter
+++ b/mk/internal/logfilter
@@ -61,7 +61,17 @@ done
 
 # No filter mode: just exec the command line
 #
-test -n "$nofilter" && exec "$@"
+if ${TEST} -n "$nofilter"; then
+    if ${TEST} -n "$logfile"; then
+	# the tricky part is to get the actual exit status of the command.
+	exec 3>&1 4>&1
+	exit `{ { "$@"; echo $? >&3; } | while read l; do
+	    echo $l >&4; echo $l>>$logfile;
+	done; } 3>&1`
+    else
+	exec "$@"
+    fi
+fi
 
 
 # Interactive message strings
